name: Gomplate Documentation Processor
description: Process action documentation using gomplate
author: Derek Rada, Matthias Fax

inputs:
  working_dir:
    description: Directory that contains the action.yml and README.md
    required: true
  template_file:
    description: Template file to use for rendering the markdown docs
    required: true
  default_template:
    description: Default template file for creating README.md
    required: true
  debug_mode:
    description: Enable debug mode
    required: false
    default: 'false'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: file-text
  color: gray-dark