name: Auto-Merge

on:
  pull_request:
    types: [auto_merge_enabled]

permissions:
  contents: write      # Required for creating commits
  pull-requests: read  # Required for reading PR details
  issues: read         # Required for reading issue comments
  statuses: write      # Required for publishing the final status
  checks: read         # Required for checking status checks
  id-token: write      # Required for Claude OIDC

jobs:
  automerge-helper:
    name: Auto-Merge Helper
    runs-on: ubuntu-latest
    environment: claude
    steps:
      - uses: matfax/verified-merge@main
        with:
          claude-code-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          check-timeout-seconds: 600
