name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_a:
    name: Test A (default template path)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Generate README.md for test_a
      uses: ./
      with:
        working_dir: examples/test_a

    - name: Verify output matches expected
      run: |
        if ! diff examples/test_a/README.md examples/test_a/README.expected.md; then
          echo "::error file=examples/test_a/README.md::Generated output does not match expected for Test A (default template path)"
          exit 1
        fi
        echo "::notice::Test A output matches expected (default template path)"

  test_b:
    name: Test B (custom template file)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Generate README.md for test_b
      uses: ./
      with:
        working_dir: examples/test_b
        template_file: custom_template.tpl

    - name: Verify output matches expected
      run: |
        if ! diff examples/test_b/README.md examples/test_b/README.expected.md; then
          echo "::error file=examples/test_b/README.md::Generated output does not match expected for Test B (custom template file)"
          exit 1
        fi
        echo "::notice::Test B output matches expected (custom template file)"

  test_c:
    name: Test C (fallback template)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Generate README.md for test_c
      uses: ./
      with:
        working_dir: examples/test_c

    - name: Verify output matches expected
      run: |
        if ! diff examples/test_c/README.md examples/test_c/README.expected.md; then
          echo "::error file=examples/test_c/README.md::Generated output does not match expected for Test C (fallback template)"
          exit 1
        fi
        echo "::notice::Test C output matches expected (fallback template)"
