name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:

  build:
    name: 'Build example docs'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - name: Should generate README.md for test_a
      uses: ./
      with:
        action_docs_working_dir: examples/test_a
        create_pr: 'false'

    - name: Should generate README.md for test_b
      uses: ./
      with:
        action_docs_working_dir: examples/test_b
        create_pr: 'false'

    - name: Generate this repos README.md
      uses: ./
      with:
        pr_title: 'docs: update action documentation'
        pr_body: |
          Automated documentation update for action-docs.
          
          This PR was created automatically when documentation changes were detected.
