name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.tpl'
      - '**/docs.yml'
      - '**/action.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - '**.tpl'
      - '**/docs.yml'
      - '**/action.yml'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Generate action documentation
        uses: matfax/action-docs@main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          base: ${{ github.base_ref || github.ref_name }}
          commit-message: 'docs: update action documentation'
          title: 'docs: Update action documentation'
          sign-commits: true
          signoff: true
          labels: |
            documentation
            auto-update
          body: |
            This pull request contains automated updates to the action README.
            
            The documentation has been regenerated from the action.yml file using the
            configured template. Please review the changes and merge if they look correct.
            
            Generated by: matfax/action-docs
          branch: docs/update-docs
          delete-branch: true
