name: Pull Request actions
on:
  - pull_request
jobs:

  build:
    name: 'Build example docs'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Should generate README.md for test_a
      uses: ./
      with:
        action_docs_working_dir: examples/test_a
        action_docs_git_push: 'false'

    - name: Should generate README.md for test_b
      uses: ./
      with:
        action_docs_working_dir: examples/test_b
        action_docs_git_push: 'false'

    - name: Generate this repos README.md
      uses: ./
